### ISSUE TITLE
rega-poll-interval funktioniert nicht

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/hm2mqtt.js#14]
Hallo,

das setzen des rega-poll-interval geht irgendwie nicht:

```
sudo hm2mqtt --rega-poll-interval 30 --ccu-address 192.168.178.205
2017-06-29 22:46:20.604 <info>  hm2mqtt 1.0.6 starting
2017-06-29 22:46:20.674 <info>  mqtt trying to connect mqtt://127.0.0.1
2017-06-29 22:46:21.017 <info>  loading names_192.168.178.205
2017-06-29 22:46:21.165 <info>  rpc rfd > init [ 'xmlrpc_bin://192.168.178.204:2127', 'hm2mqtt_rfd' ]
2017-06-29 22:46:21.223 <info>  rpc hs485d > init [ 'xmlrpc_bin://192.168.178.204:2127', 'hm2mqtt_hs485d                       ' ]
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 192.168.178.204:2127
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at doListen (net.js:1479:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

Danke

**Comment by hobbyquaker** [comment]
Hmm, der Fehler scheint aber von was anderem herzurühren. hm2mqtt beschwert sich dass 192.168.178.204:2127 bereits in Verwendung ist...

**Comment by hobbyquaker** [comment]
Verstehe ich das richtig dass dieser Fehler nur auftritt wenn Du die `--rega-poll-interval` option setzt und sonst nicht?

**Comment by juergen012** [comment]
das Problem von robdg80 hatte ich auch. Bei mir hat das löschen der mosquitto.db und das neuaufsetzten von PM2 geholfen..

**Comment by Hypnos3** [comment]
Ich hab hm2mqtt aktuell nicht mehr im Einsatz.
