### ISSUE TITLE
Applikation beendet sich, nachdem die Store hinaufgefahren wird

### ISSUE THREAD

**Issue by RF77** [hobbyquaker/hm2mqtt.js#15]
Version: 1.0.6

Nachdem ich die eine Store herauffahren will, beendet sich die Applikation.
JEQ0301936:1 entspricht  der "Store EG Süd rechts"

2017-07-02 21:29:10.824 <debug> mqtt < hm/set/Store EG Süd rechts/DIRECTION 1
/usr/lib/node_modules/hm2mqtt/index.js:319
        if (devices[i][address]) {
                      ^

TypeError: Cannot read property 'JEQ0301936:1' of undefined
    at Object.keys.forEach.i (/usr/lib/node_modules/hm2mqtt/index.js:319:23)
    at Array.forEach (native)
    at findIface (/usr/lib/node_modules/hm2mqtt/index.js:318:26)
    at rpcSet (/usr/lib/node_modules/hm2mqtt/index.js:328:19)
    at MqttClient.mqtt.on (/usr/lib/node_modules/hm2mqtt/index.js:122:9)
    at emitThree (events.js:116:13)
    at MqttClient.emit (events.js:197:7)
    at MqttClient._handlePublish (/usr/lib/node_modules/hm2mqtt/node_modules/mqtt/lib/client.js:851:12)
    at MqttClient._handlePacket (/usr/lib/node_modules/hm2mqtt/node_modules/mqtt/lib/client.js:292:12)
    at process (/usr/lib/node_modules/hm2mqtt/node_modules/mqtt/lib/client.js:248:12)

**Comment by RF77** [comment]
Passiert nicht nur mit einer Store, sondern mit allen MQTT sets. Habe weder eine neue Version bei der CCU noch ein neues Gerät hinzugefüt. Habe die CCU mal neu gestartet. Bis gestern lief es gut. Habe auch mal hm2mqtt auf einem anderen PC installiert => dasselbe, Habe auch die Versionen 1.0.5 und 1.02 probiert, ebenfalls ein Crash.
Irgendwelche Ideen?

**Comment by hobbyquaker** [comment]
Danke für den Fix, ist gemerged 👍
